### ISSUE TITLE
Get all cond_task_spec of ExclusiveGateway of BPMN file

### ISSUE THREAD

**Issue by dangduc411** [sartography/SpiffWorkflow#136]
Hi

I newbie to Python and I need get all condition of a ExclusiveGateway.
In your bpmn ExclusiveGateway example (ExclusiveGateway.bpmn), I updated sequenceFlow "Flow_0ndzufr" with Condition Type is "Expression" and Expression is "spam == "yes""

[ExclusiveGateway.zip](https://github.com/sartography/SpiffWorkflow/files/7382413/ExclusiveGateway.zip)

But when I print ExclusiveGateway "Gateway_137eb6a" as dictionary, the "cond_task_spec" only have 1 element is "Activity_09e3b3s"

```
{
    '_wf_spec': <SpiffWorkflow.bpmn.specs.BpmnProcessSpec.BpmnProcessSpec object at 0x7f4c106745f8>,
    'cancelled_event': <SpiffWorkflow.util.event.Event object at 0x7f4c0fa63eb8>,
    'choice': None,
    'completed_event': <SpiffWorkflow.util.event.Event object at 0x7f4c0fa63e80>,
    'cond_task_specs': [(<SpiffWorkflow.bpmn.specs.BpmnSpecMixin._BpmnCondition object at 0x7f4c0fa7b8d0>,'Activity_09e3b3s')],
    'data': {},
    'default_task_spec': 'Activity_0vgw12z',
    'defines': {},
    'description': None,
    'documentation': None,
    'entered_event': <SpiffWorkflow.util.event.Event object at 0x7f4c0fa63d30>,
    'extensions': {},
    'finished_event': <SpiffWorkflow.util.event.Event object at 0x7f4c0fa63ef0>,
    'id': 'exgateway_6',
    'inputs': [<SpiffWorkflow.camunda.specs.UserTask.UserTask object at 0x7f4c0fa63710>],
    'internal': False,
    'lane': None,
    'locks': [],
    'lookahead': 2,
    'loopTask': False,
    'manual': False,
    'name': 'Gateway_137eb6a',
    'outgoing_sequence_flows': {
        'Activity_09e3b3s': <SpiffWorkflow.bpmn.specs.BpmnSpecMixin.SequenceFlow object at 0x7f4c0fa7b828>,
        'Activity_0vgw12z': <SpiffWorkflow.bpmn.specs.BpmnSpecMixin.SequenceFlow object at 0x7f4c0fa63fd0>
    },
    'outgoing_sequence_flows_by_id': {
        'Flow_0ndzufr': <SpiffWorkflow.bpmn.specs.BpmnSpecMixin.SequenceFlow object at 0x7f4c0fa63fd0>,
        'Flow_1f0xngu': <SpiffWorkflow.bpmn.specs.BpmnSpecMixin.SequenceFlow object at 0x7f4c0fa7b828>
    },
    'outputs': [
        <SpiffWorkflow.camunda.specs.UserTask.UserTask object at 0x7f4c0fa7b2b0>,
        <SpiffWorkflow.camunda.specs.UserTask.UserTask object at 0x7f4c0fa7b048>
    ],
    'position': {'x': 435.0, 'y': 95.0},
    'post_assign': [],
    'pre_assign': [],
    'reached_event': <SpiffWorkflow.util.event.Event object at 0x7f4c0fa63da0>,
    'ready_event': <SpiffWorkflow.util.event.Event object at 0x7f4c0fa63e48>
}
```

This is my sample code

```
from SpiffWorkflow.bpmn.workflow import BpmnWorkflow
from SpiffWorkflow.camunda.parser.CamundaParser import CamundaParser
from SpiffWorkflow.camunda.specs.UserTask import EnumFormField, UserTask
import pprint

parser = CamundaParser()
parser.add_bpmn_file('./diagrams/ExclusiveGateway.bpmn')
spec = parser.get_spec('exgateway')

pprint.pprint(spec.task_specs['Gateway_137eb6a'].__dict__)
```

Have any way I can get all condition of ExclusiveGateway ?

**Comment by danfunk** [comment]
If you go ahead and instantiate the workflow, to get a running instance, if will give you access to a navigation tool, that might help you.

```python
workflow = BpmnWorkflow(spec)
nav = workflow.get_flat_nav_list()
```
Which will show you the full data structure, and what choices are ahead:

```
 STATE: FUTURE O
  STATE: FUTURE [Trip Info] TASK ID: 50b792c8-8d43-4c0d-8d6f-6f0da4326c35
  STATE: FUTURE X None X
 .., STATE: None -> Spam is good
 ..,.., STATE: LIKELY [Spam is good] TASK ID: ae904edb-bdc2-4b8d-9005-86a243e6a4ac
 .., STATE: None -> Spam is bad
 ..,.., STATE: MAYBE [Spam is bad] TASK ID: d94f86db-dd1f-4c1e-b2fa-eb8f81f04695
  STATE: LIKELY (EndEvent) None
  STATE: None (UnstructuredJoin) 
```

Generally speaking you would want to actually run the workflow, and allow Spiff to figure out what happens next.  That's the job it is designed to do.  Otherwise you are still basically just parsing the XML.  There are lots of fine ways to do that, but Spiff isn't trying to parse the workflow into some other easy to use structure.  It's trying to actually execute the workflow, and tell you what is happening next.

I would not try to look at some arbitrary attribute of an internal model like "cond_task_specs" in the ExclusiveGateway to give you meaningful information.  I did some deep digging, and it looks like,  for exclusive gateways, something has to be the default path.  If this is not explicitly defined, Spiff is currently setting the first encountered path as the default.  So it doesn't appear in the list of conditions.  I'm making a note of this, as it doesn't feel exactly right to me, so I'm going to add a task to fix this, and assure that we don't arbitrarily pick a default path, and error out if a gateway is encountered that doesn't offer a viable direction.
