### ISSUE TITLE
Whether to support form references

### ISSUE THREAD

**Issue by wlm77** [sartography/SpiffWorkflow#150]
Are camunda forms file supported in the activities of the process?

**Comment by danfunk** [comment]
SpiffWorkflow doesn't support the new 7.15 Camunda forms directly.   It can parse the earlier forms and make them available to a user interface.  We have an [example of parsing a form and displaying at the command line] (https://github.com/sartography/SpiffExample/blob/master/ExampleCode.py#L6).  We've taken this particular path a long way, and build a complex approval process using these forms in web applications using SpiffWorkflow.  To be blunt, I'm certain I would not do it again. I believe the future is in a different direction.

The real power of SpiffWorkflow is that it allows you to extend the parser, so that you can develop whatever user tasks you would like, and incode anything you see fit within them.  Pair this with BPMN.js, and it's extension modules, and suddenly you have a custom editor that will allow many different types of user tasks, and a parser that can read them, and pass them along to your front end code to accomplish novel and truely innovative low-code applications.

If I were starting our current project over today, I would start by adding the beautiful and robust Formly Form Editor to our authoring environment, linking or embedding these forms into our BPMN files.  Formly is a very robust tool for defining web forms, and is broadly supported in a number of popular front end frameworks.
