### ISSUE TITLE
[Question] support for `Inputs` ?

### ISSUE THREAD

**Issue by shazz** [sartography/SpiffWorkflow#266]
Hi,

In my BPMN workflow I tried to use an `Input` map but in the `BusinessRuleTask`, I did not find any way to retrieve it:

![image](https://user-images.githubusercontent.com/604708/202864530-2ea3c3a3-cda6-48c8-bc43-01bc6296e232.png)

Am I wrong or it is not supported. Will it be?

Thanks !

**Comment by shazz** [comment]
Else I started to add in node_parser:

`````python
    def parse_extensions(self, node=None):
        extensions = {}
        extra_ns = {"camunda": CAMUNDA_MODEL_NS}
        xpath = xpath_eval(self.node, extra_ns) if node is None else xpath_eval(node, extra_ns)
        extension_nodes = xpath(".//bpmn:extensionElements/camunda:properties/camunda:property")
        for node in extension_nodes:
            extensions[node.get("name")] = node.get("value")
        return extensions

    def parse_extensions_inputs(self, node=None):
        extensions_inputs = {}
        extra_ns = {"camunda": CAMUNDA_MODEL_NS}
        xpath = xpath_eval(self.node, extra_ns) if node is None else xpath_eval(node, extra_ns)
        extension_inout_nodes = xpath(".//bpmn:extensionElements/camunda:inputOutput/camunda:inputParameter")
        for node in extension_inout_nodes:
            extensions_inputs[node.get("name")] = {}
            if first(xpath(".//bpmn:extensionElements/camunda:inputOutput/camunda:inputParameter/camunda:map")):
                entries = xpath(".//bpmn:extensionElements/camunda:inputOutput/camunda:inputParameter/camunda:map/camunda:entry")
                for entry in entries:
                    extensions_inputs[node.get("name")][entry.get("key")] = entry.text
        return extensions_inputs
````

**Comment by danfunk** [comment]
We are _not_ trying to re-implement Camunda's proprietary efforts in SpiffWorkflow.  
Rather than trying to get Camunda's inputs and outputs working, perhaps we could talk about what feature this is providing you, and if it's the right method for achieving that goal.
If I am reading this correctly, you would like to create a map?  Why not do this in Script Task?  

It seems a good time to point you at SpiffWorkflow's custom properties panel (https://github.com/sartography/bpmn-js-spiffworkflow) -- this provides a properties panel that will work with spiffworkflow -- and it provides some powerful data management tools that you might find helpful.
